/**
 * `<base>/llms.txt`: the whole API surface as plain Markdown.
 *
 * starlight-llms-txt walks the `docs` content collection, which cannot see
 * injected routes (PLAN.md decision 10), so we render our own. It is also useful
 * on its own: one URL that gives a model the entire API.
 */

import type { APIRoute } from 'astro';
import context from 'virtual:starlight-pydocs/context';

import { renderPackageMarkdown } from '../lib/markdown-doc.ts';
import { packageModelForPathname } from '../libs/route.ts';

export const GET: APIRoute = async ({ site, url }) => {
  const { pkg, model } = await packageModelForPathname(context, url.pathname);
  const origin = site === undefined ? url.origin : site.href.replace(/\/$/, '');
  const header = [
    `# ${pkg.label}`,
    '',
    `> API reference for the Python package \`${pkg.name}\`, generated by starlight-pydocs.`,
    `> Rendered pages: ${origin}${context.siteBase}/${pkg.base}/`,
    '',
  ].join('\n');

  return new Response(`${header}\n${renderPackageMarkdown(model, { includeSource: true })}`, {
    headers: { 'content-type': 'text/markdown; charset=utf-8' },
  });
};
