/**
 * The shape of `virtual:starlight-pydocs/context` — the only data carried
 * through a virtual module. Deliberately small: configuration and file paths,
 * never the dumps themselves (they are megabytes; `lib/data.ts` reads them
 * lazily from disk, server-side).
 *
 * Everything a route, endpoint or middleware needs at render time is here, and
 * everything here survives `JSON.stringify` — the virtual module is generated by
 * serialising this object.
 */

import type {
  DocstringStyle,
  NormalisedFilters,
  NormalisedMembers,
  NormalisedSourceLink,
  PydocsConfig,
  PydocsSidebarConfig,
} from './config.ts';
import { stripLeadingAndTrailingSlashes } from './paths.ts';

export interface PydocsPackageContext {
  /** Python import name of the documented package. */
  name: string;
  /** URL base for the generated pages, without leading or trailing slashes (e.g. `api/demopkg`). */
  base: string;
  /** Absolute path to the griffe dump JSON for this package. */
  dumpPath: string;
  /**
   * Absolute path to the pre-rendered docstring HTML for this package, written
   * at `astro:config:done` (PLAN.md decision 7).
   */
  renderedPath: string;
  /** Docstring flavour the dump was parsed with, for display and diagnostics. */
  docstringStyle: DocstringStyle;
  /** Member selection globs, needed to build the model. */
  members: NormalisedMembers;
  /** Coarse member filters, needed to build the model. */
  filters: NormalisedFilters;
  /** Resolved source-link template, or undefined when source links are off. */
  sourceLink: NormalisedSourceLink | undefined;
  /** Sidebar presentation for this package's generated group. */
  sidebar: PydocsSidebarConfig;
}

export interface PydocsInventoryContext {
  /** Base URL that this inventory's URIs resolve against, with a trailing slash. */
  base: string;
  /** Absolute path of the cached (or local) `objects.inv`. */
  path: string;
}

export interface PydocsContext {
  packages: PydocsPackageContext[];
  /** The host project's `base` Astro setting, normalised ('' or '/prefix'). */
  siteBase: string;
  /** Astro trailingSlash setting, used when building hrefs. */
  trailingSlash: 'always' | 'never' | 'ignore';
  /** Whether the host is Starlight (true) or vanilla Astro (false). */
  starlight: boolean;
  /** Serve `symbols.json` and render the symbol search component. */
  symbolSearch: boolean;
  /** Serve the plain-Markdown rendition of the API. */
  llmsTxt: boolean;
  /** Serve this site's own `objects.inv`. */
  publishInventory: boolean;
  /** Inventories to resolve annotations against, already downloaded. */
  inventories: PydocsInventoryContext[];
  /** Absolute cache directory, for endpoints that need to write. */
  cacheDir: string;
}

export interface CreateContextOptions {
  /** Absolute dump path per package name, from the runner. */
  dumpPaths: Map<string, string>;
  /** Absolute sidecar path per package name, from `renderedSidecarPath`. */
  renderedPaths?: Map<string, string> | undefined;
  /** Astro's `base`, in any form; normalised to '' or '/prefix'. */
  siteBase: string | undefined;
  trailingSlash: 'always' | 'never' | 'ignore';
  starlight: boolean;
  /** Downloaded inventories, in configuration order. */
  inventories?: PydocsInventoryContext[] | undefined;
}

/** Build the render-time context from a validated configuration. */
export function createContext(config: PydocsConfig, options: CreateContextOptions): PydocsContext {
  const siteBase = stripLeadingAndTrailingSlashes(options.siteBase ?? '');

  return {
    packages: config.packages.map((pkg) => ({
      name: pkg.name,
      base: pkg.base,
      dumpPath: options.dumpPaths.get(pkg.name) ?? '',
      renderedPath: options.renderedPaths?.get(pkg.name) ?? '',
      docstringStyle: pkg.docstringStyle,
      members: pkg.members,
      filters: pkg.filters,
      sourceLink: pkg.sourceLink,
      sidebar: pkg.sidebar,
    })),
    siteBase: siteBase === '' ? '' : `/${siteBase}`,
    trailingSlash: options.trailingSlash,
    starlight: options.starlight,
    symbolSearch: config.symbolSearch,
    llmsTxt: config.llmsTxt,
    publishInventory: config.publishInventory,
    inventories: options.inventories ?? [],
    cacheDir: config.cacheDir,
  };
}

/** The package that owns a URL slug, or undefined when none does. */
export function packageForSlug(context: PydocsContext, slug: string): PydocsPackageContext | undefined {
  const normalised = stripLeadingAndTrailingSlashes(slug);
  return context.packages.find((pkg) => normalised === pkg.base || normalised.startsWith(`${pkg.base}/`));
}

/** Look up a package by import name. */
export function packageByName(context: PydocsContext, name: string): PydocsPackageContext | undefined {
  return context.packages.find((pkg) => pkg.name === name);
}
