/**
 * The shape of `virtual:starlight-pydocs/context`, the only data carried
 * through a virtual module. Deliberately small: configuration and file paths,
 * never the dumps themselves (they are megabytes; `lib/data.ts` reads them
 * lazily from disk, server-side).
 *
 * Everything a route, endpoint or middleware needs at render time is here, and
 * everything here survives `JSON.stringify`: the virtual module is generated by
 * serialising this object.
 */

import type {
  DocstringStyle,
  NormalisedFilters,
  NormalisedMembers,
  NormalisedSourceLink,
  PydocsConfig,
  PydocsPackageConfig,
  PydocsSidebarConfig,
} from './config.ts';
import { isInside, isUnderBase, stripLeadingAndTrailingSlashes } from './paths.ts';

export interface PydocsPackageContext {
  /** Python import name of the documented package. */
  name: string;
  /**
   * URL base for the generated pages, without leading or trailing slashes (e.g.
   * `api/demopkg`). Unique per entry, so it (not `name`) identifies a package
   * everywhere at render time.
   */
  base: string;
  /** Display name for this entry, defaulting to `name`. */
  label: string;
  /** Absolute path to the griffe dump JSON for this package. */
  dumpPath: string;
  /**
   * Absolute path to the pre-rendered docstring HTML for this package, written
   * at `astro:config:done` (ARCHITECTURE.md decision 7).
   */
  renderedPath: string;
  /**
   * Absolute path to the "added in" labels for this package, written at setup
   * from dumps of the configured version refs (ARCHITECTURE.md decision 12). Empty when
   * the package has no `versions.refs`.
   */
  versionsPath: string;
  /** Docstring flavour the dump was parsed with, for display and diagnostics. */
  docstringStyle: DocstringStyle;
  /** Member selection globs, needed to build the model. */
  members: NormalisedMembers;
  /** Coarse member filters, needed to build the model. */
  filters: NormalisedFilters;
  /** Resolved source-link template, or undefined when source links are off. */
  sourceLink: NormalisedSourceLink | undefined;
  /** Sidebar presentation for this package's generated group. */
  sidebar: PydocsSidebarConfig;
  /**
   * Release page per "added in" label, e.g. `1.9` → the page for tag `v1.9.0`.
   * Built here because it needs both halves of the configuration: the label and
   * git ref come from `versions.refs`, the forge from `sourceLink`. Empty when
   * either is missing, and the label then renders as plain text.
   */
  versionReleases: Record<string, string>;
}

export interface PydocsInventoryContext {
  /** Base URL that this inventory's URIs resolve against, with a trailing slash. */
  base: string;
  /** Absolute path of the cached (or local) `objects.inv`. */
  path: string;
}

export interface PydocsContext {
  packages: PydocsPackageContext[];
  /** The host project's `base` Astro setting, normalised ('' or '/prefix'). */
  siteBase: string;
  /** Astro trailingSlash setting, used when building hrefs. */
  trailingSlash: 'always' | 'never' | 'ignore';
  /** Whether the host is Starlight (true) or vanilla Astro (false). */
  starlight: boolean;
  /** Serve `symbols.json` and render the symbol search component. */
  symbolSearch: boolean;
  /** Serve the plain-Markdown rendition of the API. */
  llmsTxt: boolean;
  /** Serve this site's own `objects.inv`. */
  publishInventory: boolean;
  /** Inventories to resolve annotations against, already downloaded. */
  inventories: PydocsInventoryContext[];
  /** Absolute cache directory, for endpoints that need to write. */
  cacheDir: string;
  /** Shiki themes signatures are highlighted with, light and dark. */
  shikiThemes: ShikiThemes;
}

/**
 * A light/dark theme pair for Shiki, as names or inline theme objects.
 *
 * Always a pair, even when the host configured one theme: the renderer asks
 * Shiki for `--shiki-light` and `--shiki-dark` variables in every case, so the
 * stylesheet has one rule per colour scheme rather than two code paths.
 */
export interface ShikiThemes {
  light: string | Record<string, unknown>;
  dark: string | Record<string, unknown>;
}

export interface CreateContextOptions {
  /** Absolute dump path per package base, from the runner. */
  dumpPaths: Map<string, string>;
  /** Absolute sidecar path per package base, from `renderedSidecarPath`. */
  renderedPaths?: Map<string, string> | undefined;
  /** Absolute version-annotation sidecar path per package base, where there is one. */
  versionsPaths?: Map<string, string> | undefined;
  /** Astro's `base`, in any form; normalised to '' or '/prefix'. */
  siteBase: string | undefined;
  trailingSlash: 'always' | 'never' | 'ignore';
  starlight: boolean;
  /** Downloaded inventories, in configuration order. */
  inventories?: PydocsInventoryContext[] | undefined;
  /** `astroConfig.markdown.shikiConfig`, for the signature highlighter. */
  shikiConfig?: unknown;
}

/** Build the render-time context from a validated configuration. */
export function createContext(config: PydocsConfig, options: CreateContextOptions): PydocsContext {
  const siteBase = stripLeadingAndTrailingSlashes(options.siteBase ?? '');

  return {
    packages: config.packages.map((pkg) => ({
      name: pkg.name,
      base: pkg.base,
      label: pkg.label,
      dumpPath: options.dumpPaths.get(pkg.base) ?? '',
      renderedPath: options.renderedPaths?.get(pkg.base) ?? '',
      versionsPath: options.versionsPaths?.get(pkg.base) ?? '',
      docstringStyle: pkg.docstringStyle,
      members: pkg.members,
      filters: pkg.filters,
      sourceLink: pkg.sourceLink,
      sidebar: pkg.sidebar,
      versionReleases: versionReleasesFor(pkg),
    })),
    siteBase: siteBase === '' ? '' : `/${siteBase}`,
    trailingSlash: options.trailingSlash,
    starlight: options.starlight,
    symbolSearch: config.symbolSearch,
    llmsTxt: config.llmsTxt,
    publishInventory: config.publishInventory,
    inventories: options.inventories ?? [],
    cacheDir: config.cacheDir,
    shikiThemes: shikiThemesFrom(options.shikiConfig),
  };
}

const DEFAULT_SHIKI_THEMES: ShikiThemes = { light: 'github-light', dark: 'github-dark' };

/** Astro fills this in when the host says nothing, so it cannot mean "chosen". */
const ASTRO_DEFAULT_SHIKI_THEME = 'github-dark';

/** A theme is usable here only if `JSON.stringify` can carry it into the build. */
function usableTheme(value: unknown): string | Record<string, unknown> | undefined {
  if (typeof value === 'string' && value !== '') return value;
  if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
    return value as Record<string, unknown>;
  }
  return undefined;
}

/**
 * Pick the light/dark pair signatures are highlighted with.
 *
 * `markdown.shikiConfig.themes` is the only setting that says something about
 * both colour schemes, so it wins outright. A single `theme` is used for both
 * only when the host actually chose it: Astro defaults that field to a dark
 * theme, and Starlight sites leave it alone because their prose code goes
 * through Expressive Code, so honouring the default would paint every
 * signature in dark colours on a light page.
 */
function shikiThemesFrom(shikiConfig: unknown): ShikiThemes {
  if (typeof shikiConfig !== 'object' || shikiConfig === null) return DEFAULT_SHIKI_THEMES;
  const { theme, themes } = shikiConfig as { theme?: unknown; themes?: unknown };
  const pair = typeof themes === 'object' && themes !== null ? (themes as Record<string, unknown>) : {};
  const light = usableTheme(pair['light']);
  const dark = usableTheme(pair['dark']);
  if (light !== undefined && dark !== undefined) return { light, dark };

  const single = usableTheme(theme);
  if (single === undefined || single === ASTRO_DEFAULT_SHIKI_THEME) return DEFAULT_SHIKI_THEMES;
  return { light: single, dark: single };
}

function versionReleasesFor(pkg: PydocsPackageConfig): Record<string, string> {
  const template = pkg.sourceLink?.releaseTemplate;
  if (template === undefined) return {};
  return Object.fromEntries(
    pkg.versions.refs.map(({ label, ref }) => [label, template.replace('{ref}', encodeURIComponent(ref))]),
  );
}

/** The package that owns a URL slug, or undefined when none does. */
export function packageForSlug(context: PydocsContext, slug: string): PydocsPackageContext | undefined {
  const normalised = stripLeadingAndTrailingSlashes(slug);
  return context.packages.find((pkg) => isUnderBase(normalised, pkg.base));
}

/** Look up a package by its base, the identity render-time code is keyed on. */
export function packageByBase(context: PydocsContext, base: string): PydocsPackageContext | undefined {
  const normalised = stripLeadingAndTrailingSlashes(base);
  return context.packages.find((pkg) => pkg.base === normalised);
}

/** Every configured entry documenting the package with this import name. */
export function packagesByName(context: PydocsContext, name: string): PydocsPackageContext[] {
  return context.packages.filter((pkg) => pkg.name === name);
}

/**
 * The outcome of resolving something a human wrote (a `package` prop, a dotted
 * object path) onto one configured entry.
 *
 * `ambiguous` exists because an import name is not an identity: the same package
 * documented at two bases (one version at each) answers to one name, and only
 * the base says which entry is meant.
 */
export type PackageMatch =
  | { kind: 'match'; pkg: PydocsPackageContext }
  | { kind: 'ambiguous'; name: string; bases: string[] }
  | { kind: 'none' };

function matchOne(candidates: PydocsPackageContext[], name: string): PackageMatch {
  const [first] = candidates;
  if (first === undefined) return { kind: 'none' };
  if (candidates.length > 1) {
    return { kind: 'ambiguous', name, bases: candidates.map((pkg) => pkg.base) };
  }
  return { kind: 'match', pkg: first };
}

/**
 * Resolve a package reference as written by a user: a base first, then an import
 * name.
 *
 * Bases win because they are unambiguous, and a base can never be mistaken for
 * an import name (it contains a slash unless the site puts a package at a
 * single-segment base, in which case that base is still the more specific
 * answer).
 */
export function matchPackageReference(context: PydocsContext, reference: string): PackageMatch {
  const byBase = packageByBase(context, reference);
  if (byBase !== undefined) return { kind: 'match', pkg: byBase };
  return matchOne(packagesByName(context, reference), reference);
}

/**
 * The package a dotted object path belongs to.
 *
 * Longest name first, so `demopkg.sub` wins over `demopkg` when both are
 * configured; entries sharing that name are ambiguous.
 */
export function matchPackageForDottedPath(context: PydocsContext, dottedPath: string): PackageMatch {
  const names = [...new Set(context.packages.map((pkg) => pkg.name))].sort((left, right) => right.length - left.length);
  const name = names.find((candidate) => isInside(dottedPath, candidate));
  if (name === undefined) return { kind: 'none' };
  return matchOne(packagesByName(context, name), name);
}
