/**
 * The shape of `virtual:starlight-pydocs/context`, the only data carried
 * through a virtual module. Deliberately small: configuration and file paths,
 * never the dumps themselves (they are megabytes; `lib/data.ts` reads them
 * lazily from disk, server-side).
 *
 * Everything a route, endpoint or middleware needs at render time is here, and
 * everything here survives `JSON.stringify`: the virtual module is generated by
 * serialising this object.
 */

import type {
  DocstringStyle,
  NormalisedFilters,
  NormalisedMembers,
  NormalisedSourceLink,
  PydocsConfig,
  PydocsSidebarConfig,
} from './config.ts';
import { isInside, isUnderBase, stripLeadingAndTrailingSlashes } from './paths.ts';

export interface PydocsPackageContext {
  /** Python import name of the documented package. */
  name: string;
  /**
   * URL base for the generated pages, without leading or trailing slashes (e.g.
   * `api/demopkg`). Unique per entry, so it (not `name`) identifies a package
   * everywhere at render time.
   */
  base: string;
  /** Display name for this entry, defaulting to `name`. */
  label: string;
  /** Absolute path to the griffe dump JSON for this package. */
  dumpPath: string;
  /**
   * Absolute path to the pre-rendered docstring HTML for this package, written
   * at `astro:config:done` (ARCHITECTURE.md decision 7).
   */
  renderedPath: string;
  /**
   * Absolute path to the "added in" labels for this package, written at setup
   * from dumps of the configured version refs (ARCHITECTURE.md decision 12). Empty when
   * the package has no `versions.refs`.
   */
  versionsPath: string;
  /** Docstring flavour the dump was parsed with, for display and diagnostics. */
  docstringStyle: DocstringStyle;
  /** Member selection globs, needed to build the model. */
  members: NormalisedMembers;
  /** Coarse member filters, needed to build the model. */
  filters: NormalisedFilters;
  /** Resolved source-link template, or undefined when source links are off. */
  sourceLink: NormalisedSourceLink | undefined;
  /** Sidebar presentation for this package's generated group. */
  sidebar: PydocsSidebarConfig;
}

export interface PydocsInventoryContext {
  /** Base URL that this inventory's URIs resolve against, with a trailing slash. */
  base: string;
  /** Absolute path of the cached (or local) `objects.inv`. */
  path: string;
}

export interface PydocsContext {
  packages: PydocsPackageContext[];
  /** The host project's `base` Astro setting, normalised ('' or '/prefix'). */
  siteBase: string;
  /** Astro trailingSlash setting, used when building hrefs. */
  trailingSlash: 'always' | 'never' | 'ignore';
  /** Whether the host is Starlight (true) or vanilla Astro (false). */
  starlight: boolean;
  /** Serve `symbols.json` and render the symbol search component. */
  symbolSearch: boolean;
  /** Serve the plain-Markdown rendition of the API. */
  llmsTxt: boolean;
  /** Serve this site's own `objects.inv`. */
  publishInventory: boolean;
  /** Inventories to resolve annotations against, already downloaded. */
  inventories: PydocsInventoryContext[];
  /** Absolute cache directory, for endpoints that need to write. */
  cacheDir: string;
}

export interface CreateContextOptions {
  /** Absolute dump path per package base, from the runner. */
  dumpPaths: Map<string, string>;
  /** Absolute sidecar path per package base, from `renderedSidecarPath`. */
  renderedPaths?: Map<string, string> | undefined;
  /** Absolute version-annotation sidecar path per package base, where there is one. */
  versionsPaths?: Map<string, string> | undefined;
  /** Astro's `base`, in any form; normalised to '' or '/prefix'. */
  siteBase: string | undefined;
  trailingSlash: 'always' | 'never' | 'ignore';
  starlight: boolean;
  /** Downloaded inventories, in configuration order. */
  inventories?: PydocsInventoryContext[] | undefined;
}

/** Build the render-time context from a validated configuration. */
export function createContext(config: PydocsConfig, options: CreateContextOptions): PydocsContext {
  const siteBase = stripLeadingAndTrailingSlashes(options.siteBase ?? '');

  return {
    packages: config.packages.map((pkg) => ({
      name: pkg.name,
      base: pkg.base,
      label: pkg.label,
      dumpPath: options.dumpPaths.get(pkg.base) ?? '',
      renderedPath: options.renderedPaths?.get(pkg.base) ?? '',
      versionsPath: options.versionsPaths?.get(pkg.base) ?? '',
      docstringStyle: pkg.docstringStyle,
      members: pkg.members,
      filters: pkg.filters,
      sourceLink: pkg.sourceLink,
      sidebar: pkg.sidebar,
    })),
    siteBase: siteBase === '' ? '' : `/${siteBase}`,
    trailingSlash: options.trailingSlash,
    starlight: options.starlight,
    symbolSearch: config.symbolSearch,
    llmsTxt: config.llmsTxt,
    publishInventory: config.publishInventory,
    inventories: options.inventories ?? [],
    cacheDir: config.cacheDir,
  };
}

/** The package that owns a URL slug, or undefined when none does. */
export function packageForSlug(context: PydocsContext, slug: string): PydocsPackageContext | undefined {
  const normalised = stripLeadingAndTrailingSlashes(slug);
  return context.packages.find((pkg) => isUnderBase(normalised, pkg.base));
}

/** Look up a package by its base, the identity render-time code is keyed on. */
export function packageByBase(context: PydocsContext, base: string): PydocsPackageContext | undefined {
  const normalised = stripLeadingAndTrailingSlashes(base);
  return context.packages.find((pkg) => pkg.base === normalised);
}

/** Every configured entry documenting the package with this import name. */
export function packagesByName(context: PydocsContext, name: string): PydocsPackageContext[] {
  return context.packages.filter((pkg) => pkg.name === name);
}

/**
 * The outcome of resolving something a human wrote (a `package` prop, a dotted
 * object path) onto one configured entry.
 *
 * `ambiguous` exists because an import name is not an identity: the same package
 * documented at two bases (one version at each) answers to one name, and only
 * the base says which entry is meant.
 */
export type PackageMatch =
  | { kind: 'match'; pkg: PydocsPackageContext }
  | { kind: 'ambiguous'; name: string; bases: string[] }
  | { kind: 'none' };

function matchOne(candidates: PydocsPackageContext[], name: string): PackageMatch {
  const [first] = candidates;
  if (first === undefined) return { kind: 'none' };
  if (candidates.length > 1) {
    return { kind: 'ambiguous', name, bases: candidates.map((pkg) => pkg.base) };
  }
  return { kind: 'match', pkg: first };
}

/**
 * Resolve a package reference as written by a user: a base first, then an import
 * name.
 *
 * Bases win because they are unambiguous, and a base can never be mistaken for
 * an import name (it contains a slash unless the site puts a package at a
 * single-segment base, in which case that base is still the more specific
 * answer).
 */
export function matchPackageReference(context: PydocsContext, reference: string): PackageMatch {
  const byBase = packageByBase(context, reference);
  if (byBase !== undefined) return { kind: 'match', pkg: byBase };
  return matchOne(packagesByName(context, reference), reference);
}

/**
 * The package a dotted object path belongs to.
 *
 * Longest name first, so `demopkg.sub` wins over `demopkg` when both are
 * configured; entries sharing that name are ambiguous.
 */
export function matchPackageForDottedPath(context: PydocsContext, dottedPath: string): PackageMatch {
  const names = [...new Set(context.packages.map((pkg) => pkg.name))].sort((left, right) => right.length - left.length);
  const name = names.find((candidate) => isInside(dottedPath, candidate));
  if (name === undefined) return { kind: 'none' };
  return matchOne(packagesByName(context, name), name);
}
